name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: eu-north-1  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Set AWS region using AWS CLI
      - name: Set AWS region
        run: aws configure set region eu-north-1

      - name: Log in to Amazon ECR
        id: login-ecr
        run: aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build and push Docker image
        id: build-image
        run: |
          # Get the ECR repository URI
          REPOSITORY_URI=$(aws ecr describe-repositories --repository-names ${{ secrets.ECR_REPOSITORY }} --query "repositories[0].repositoryUri" --output text)

          # Build the Docker image
          docker build -t $REPOSITORY_URI:latest .

          # Push the Docker image to ECR
          docker push $REPOSITORY_URI:latest
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
